# Generated by Django 5.2.7 on 2025-11-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_valu',
            new_name='variation_value',
        ),
    ]
